name: Build Manylinux Wheels

on:
  workflow_dispatch:
  
jobs:
  build-manylinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['cp37-cp37m', 'cp38-cp38', 'cp39-cp39', 'cp310-cp310', 'cp311-cp311', 'cp312-cp312']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build manylinux wheel
      run: |
        docker build -t tensorfrost-manylinux .
        docker run --rm -e PYTHON_VERSION=${{ matrix.python-version }} -v $(pwd):/io tensorfrost-manylinux

    - name: Upload wheels as artifact
      uses: actions/upload-artifact@v2
      with:
        name: manylinux-wheels
        path: wheelhouse/*.whl
