name: Build macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Also install build, cmake, pybind11, etc. as needed
          pip install cmake build

      - name: Configure and build with CMake
        run: |
          # If you need to point CMake to your Python, do something like:
          export PYTHON_EXECUTABLE=$(which python)
          python --version

          cmake \
            -DPYBIND11_PYTHON_VERSION="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')" \
            -DPython3_EXECUTABLE="$PYTHON_EXECUTABLE" \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=Release

          cmake --build build --config Release

      - name: Build wheel
        run: |
          python -m build -w ./Python

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels-py${{ matrix.python-version }}
          path: Python/dist/*.whl