name: Download Artifacts

on:
  workflow_call:

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            
            async function findWorkflow(partialName) {
              const workflows = await github.rest.actions.listRepoWorkflows({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              return workflows.data.workflows.find(w => w.name.includes(partialName));
            }
            
            async function downloadArtifact(workflowPartialName, artifactName) {
              const workflow = await findWorkflow(workflowPartialName);
              if (!workflow) return false;
            
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow.id,
                status: 'success'
              });
            
              if (runs.data.total_count === 0) return false;
            
              const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: runs.data.workflow_runs[0].id
              });
            
              const matchingArtifacts = artifacts.data.artifacts.filter(a => a.name.startsWith(artifactName));
              if (matchingArtifacts.length === 0) return false;
            
              for (const artifact of matchingArtifacts) {
                const download = await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
                });
            
                fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifact.name}.zip`, Buffer.from(download.data));
                console.log(`Downloaded ${artifact.name}.zip`);
              }
              return true;
            }
            
            await downloadArtifact("MacOS", "macos-wheels");
            await downloadArtifact("Windows", "windows-wheels");
            await downloadArtifact("Manylinux", "manylinux-wheels");

      - name: Unzip artifacts
        run: |
          mkdir -p ./wheels
          for zip in *.zip; do
            if [ -f "$zip" ]; then
              unzip -d ./wheels "$zip"
              echo "Unzipped $zip"
            fi
          done

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-wheels
          path: ./wheels
          retention-days: 1
