name: Upload to TestPyPI

on:
  workflow_run:
    workflows: ["Build Windows Wheels", "Build Manylinux Wheels"]
    types:
      - completed

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifacts
      uses: actions/github-script@v6
      with:
        script: |
          var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: ${{github.event.workflow_run.id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "windows-wheels" || artifact.name == "manylinux-wheels"
          });
          var downloadPromises = matchArtifact.map(async (artifact) => {
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: artifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/' + artifact.name + '.zip', Buffer.from(download.data));
          });
          await Promise.all(downloadPromises);

    - name: Unzip artifacts
      run: |
        unzip -d windows-wheels windows-wheels.zip
        unzip -d manylinux-wheels manylinux-wheels.zip

    - name: Install Twine
      run: pip install twine

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_REPO_TOKEN }}
      run: |
        python -m twine upload --repository-url https://test.pypi.org/legacy/ windows-wheels/*.whl manylinux-wheels/*.whl --verbose --disable-progress-bar
