name: Upload to TestPyPI

on:
  workflow_dispatch:

jobs:
  download-artifacts:
    uses: ./.github/workflows/download_artifacts.yml
    
  upload-to-pypi:
    needs: download-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Download wheel artifacts
      uses: actions/download-artifact@v2
      with:
        name: all-wheels
        path: ./wheels
        
    - name: Install Twine
      run: pip install twine

    - name: Upload to PyPI
      run: |
        REPO_URL="https://test.pypi.org/legacy/"
        twine upload --repository-url $REPO_URL --skip-existing wheels/* --verbose --disable-progress-bar -u __token__ -p ${{ secrets.TEST_PYPI_REPO_TOKEN }}
