name: Upload to TestPyPI

on:
  workflow_dispatch:

jobs:
  download-artifacts:
    uses: ./.github/workflows/download_artifacts.yml
    
  upload-to-pypi:
    needs: download-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Twine
      run: pip install twine

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_REPO_TOKEN }}
      run: |
        if ls */*.whl 1> /dev/null 2>&1; then
          python -m twine upload --repository-url https://test.pypi.org/legacy/ */*.whl --verbose --disable-progress-bar
        else
          echo "No wheel files found to upload"
          exit 1
        fi
